# Generated by Django 4.2 on 2024-07-30 04:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='uploads/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ExtractedData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extracted_data', models.TextField(default=[])),
                ('uploaded_image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.uploadedimage')),
            ],
            options={
                'verbose_name': 'ExtractedData',
                'verbose_name_plural': 'ExtractedData',
            },
        ),
    ]
