# Generated by Django 4.2 on 2024-07-30 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='extracteddata',
            name='gujarati',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='extracteddata',
            name='gujarati_english',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='extracteddata',
            name='hindi',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='extracteddata',
            name='hinglish',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='extracteddata',
            name='malayalam',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='extracteddata',
            name='malayalam_english',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='extracteddata',
            name='marathi',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='extracteddata',
            name='marathi_english',
            field=models.TextField(blank=True, null=True),
        ),
    ]
