# Generated by Django 5.0.7 on 2024-08-01 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_extracteddata_gujarati_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CachedData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('english_sentence', models.TextField(default='')),
                ('language_code', models.TextField(default='')),
                ('translation', models.TextField(default='')),
            ],
            options={
                'verbose_name': 'CachedData',
                'verbose_name_plural': 'CachedData',
            },
        ),
    ]
