# Generated by Django 5.0.7 on 2024-08-02 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_cacheddata'),
    ]

    operations = [
        migrations.AddField(
            model_name='cacheddata',
            name='google_translation',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='cacheddata',
            name='sushi_test_result',
            field=models.TextField(default=''),
        ),
    ]
