# Generated by Django 5.0.7 on 2024-08-05 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_remove_extracteddata_gujarati_english_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cacheddata',
            name='english_sentence',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='cacheddata',
            name='google_translation',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='cacheddata',
            name='language_code',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='cacheddata',
            name='sushi_test_result',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='cacheddata',
            name='translation',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
